name = "hey-discord-the-pipeline-failed"
account_id = ""
zone_id = ""

route = "gitlab-notifications.fxoi.io"
workers_dev = false

compatibility_date = "2022-05-26"

kv_namespaces = [
    { binding = "CONFIG", id = "<Add it here>" }
]
